export const FETCH_ITEMS = 'FETCH_ITEMS'
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED'
export const ASYNC_FETCH_ITEMS = 'ASYNC_FETCH_ITEMS'